name: colorz
description: "🎨 Color constants which represent named colors from colornames.org."
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.13
  console: ^3.1.0
  http: ^0.12.0+4
  mustache: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
